version: '3'

services:
  mysql:
    command: mysqld --default-authentication-plugin=mysql_native_password
    image: mysql:5.6
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=base_de_datos
      - MYSQL_USER=user
      - MYSQL_PASSWORD=Tuclave
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - app-net
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./config/apache/apache2.conf:/etc/apache2/apache2.conf
      - ./var/www/html:/var/www/
      - ./config/apache/apache-vhosts.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./config/hosts:/etc/hosts
      - ./config/php/php.conf:/etc/php/7.0/fpm/php.ini
    restart: always
    tty: true
    networks:
      - app-net

    depends_on:
      - mysql

networks:
  app-net:

volumes:
  mysql_data: