version: '3'

services:
  mysql:
    command: mysqld --default-authentication-plugin=mysql_native_password
    image: mysql:8
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=base_de_datos
      - MYSQL_USER=user
      - MYSQL_PASSWORD=Tuclave
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - app-net
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"

    volumes:
      - ./html:/var/www/html
    restart: always
    tty: true
    networks:
      - app-net

    depends_on:
      - mysql

networks:
  app-net:

volumes:
  mysql_data: